export const countryOptions: Array<{label: string; key: string}> = [
  {label: 'United States', key: 'US'},
  {label: 'Australia', key: 'AU'},
  {label: 'Canada', key: 'CA'},
  {label: 'United Kingdom', key: 'GB'},

  {label: 'Austria', key: 'AT'},
  {label: 'Belgium', key: 'BE'},
  {label: 'Denmark', key: 'DK'},
  {label: 'Finland', key: 'FI'},
  {label: 'France', key: 'FR'},
  {label: 'Germany', key: 'DE'},
  {label: 'Ireland', key: 'IE'},
  {label: 'Italy', key: 'IT'},
  {label: 'Luxembourg', key: 'LU'},
  {label: 'Netherlands', key: 'NL'},
  {label: 'Norway', key: 'NO'},
  {label: 'Portugal', key: 'PT'},
  {label: 'Spain', key: 'ES'},
  {label: 'Sweden', key: 'SE'},
  {label: 'Switzerland', key: 'CH'},
];
